repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        language: system
        entry: poetry run black
        types: [python]
    -   id: flake8
        name: flake8
        language: system
        entry: poetry run flake8 --max-line-length 88 --exclude __init__.py --ignore E203
        types: [python]
    -   id: isort
        name: isort
        language: system
        entry: poetry run isort --profile black -s __init__.py --df
        types: [python]
    -   id: pytest
        name: pytest
        language: system
        entry: poetry run pytest
        types: [python]
        always_run: true
        pass_filenames: false
